
services:
  database:
    build: ./database/
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: hive
    volumes:
      - sql-data:/var/lib/mysql
    networks:
      hive-network:
        aliases:
          - mysql-hive-db

  webserver:
    build: ./frontend/
    depends_on:
      - database
    command: php -S 0.0.0.0:80
    ports:
      - "80:80"
    networks:
      - hive-network

  jenkins:
    build: ./jenkins/
    ports:
      - "8080:8080"
    environment:
      JENKINS_ADMIN_ID: "root"
      JENKINS_ADMIN_PASSWORD: "root"
      JENKINS_PORT: 8080
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - hive-network


volumes:
  sql-data:
  jenkins-data:

networks:
  hive-network: